[terminal.shell]
program = "/usr/bin/zsh"

[font]
normal                = { family = "FiraCodeNerdFont Mono", style = "Regular" }
bold                  = { family = "FiraCodeNerdFont Mono", style = "Bold" }
italic                = { family = "FiraCodeNerdFont Mono", style = "Italic" }
bold_italic           = { family = "FiraCodeNerdFont Mono", style = "Bold Italic" }
size                  = 11.25
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

[window]
padding.x = 10
padding.y = 10
decorations = "Full"
dynamic_padding = true
opacity = 0.9
startup_mode = "Fullscreen"

[colors.primary]
background = "#1e2027"
foreground = "#d8dee9"
