[package_management]
manager = "uv"

[mcp]
presets = []

[mcp.mcpServers]

[formatting]
line_length = 90

[keymap]
destructive_delete = true
preset = "vim"

[keymap.overrides]

[ai]
rules = ""
mode = "manual"

[ai.models]
displayed_models = []
custom_models = []

[completion]
activate_on_typing = true
copilot = false

[server]
browser = "default"
follow_symlink = false

[save]
autosave_delay = 5000
autosave = "after_delay"
format_on_save = false

[experimental]

[runtime]
on_cell_change = "autorun"
default_sql_output = "auto"
default_auto_download = []
watcher_on_save = "lazy"
output_max_bytes = 8000000
reactive_tests = true
std_stream_max_bytes = 1000000
auto_reload = "off"
auto_instantiate = true

[language_servers.pylsp]
enable_flake8 = false
enable_pyflakes = false
enable_ruff = true
enabled = true
enable_pydocstyle = false
enable_pylint = false
enable_mypy = true

[language_servers.ty]

[language_servers.basedpyright]

[display]
reference_highlighting = true
default_table_page_size = 10
code_editor_font_size = 16
cell_output = "below"
theme = "dark"
dataframes = "rich"
default_width = "full"
default_table_max_columns = 50

[diagnostics]

[snippets]
include_default_snippets = true
custom_paths = []
