[runtime]
output_max_bytes = 8000000
default_sql_output = "auto"
watcher_on_save = "lazy"
on_cell_change = "autorun"
auto_reload = "lazy"
std_stream_max_bytes = 1000000
reactive_tests = true
auto_instantiate = true
default_auto_download = []

[completion]
copilot = false
activate_on_typing = true

[display]
default_width = "full"
dataframes = "rich"
default_table_page_size = 10
cell_output = "below"
code_editor_font_size = 17
reference_highlighting = true
theme = "dark"
default_table_max_columns = 50

[formatting]
line_length = 80

[snippets]
include_default_snippets = true
custom_paths = []

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_pydocstyle = false
enable_pyflakes = false
enable_mypy = true
enabled = true
enable_pylint = false
enable_ruff = true
enable_flake8 = false

[ai]
inline_tooltip = false
rules = ""
mode = "manual"

[ai.models]
displayed_models = []
custom_models = []

[save]
autosave_delay = 5000
format_on_save = true
autosave = "after_delay"

[server]
follow_symlink = false
browser = "default"

[experimental]

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[package_management]
manager = "uv"

[mcp]
presets = []

[mcp.mcpServers]

[diagnostics]
